#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/envs/py3-cerebmodels/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/envs/py3-cerebmodels/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/cereb/cerebmodels/models/cells/PC2003Khaliq/mod_files/x86_64/.libs/libnrnmech.so" "$@"
